/**
 * Root layout for the Next.js app.
 * - Loads custom Google fonts (Geist Sans and Geist Mono) and makes them available as CSS variables.
 * - Applies global CSS styles.
 * - Sets default site metadata (title & description).
 * - Wraps all pages in a consistent HTML and body structure with antialiasing and custom fonts.
 * (Antialiasing is a technique used in computer graphics and digital typography to make edges and curves look smoother and less jagged.)
 
- layout.tsx is automatically used by Next.js to wrap page.tsx.

- You don’t need to manually import layout.tsx in page.tsx.

- The folder hierarchy decides which layouts apply.
*/


// Import type for page metadata (title, description, etc.)
import type { Metadata } from "next";

// Import two Google fonts (Geist Sans and Geist Mono) from next/font/google
import { Geist, Geist_Mono } from "next/font/google";

// Import global CSS styles
import "./globals.css";

// Load Geist Sans font with a custom CSS variable name
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load Geist Mono font with a custom CSS variable name
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata for the entire application (used by Next.js)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the RootLayout component: the layout wrapper for all pages
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> {/* Set HTML language attribute */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // Apply loaded font variables and antialiasing to the whole body
      >
        {children} {/* Render all child components inside this layout */}
      </body>
    </html>
  );
}
